version: 2

defaults: &defaults
  machine:
    xcode:
      version: "8.3"
  working_directory: ~/Superb

jobs:
  lint:
    <<: *defaults
    steps:
      - checkout
      - git fetch --unshallow 2>/dev/null || true
      - pod lib lint

  test:
    <<: *defaults
    steps:
      - checkout
      - run: bin/bootstrap
      - run: bin/copy-secrets
      - run: bin/test

workflows:
  version: 2
  test:
    jobs:
      - test
      - lint
