version: 2

jobs:
  checkout:
    machine:
      xcode:
        version: "8.3"
    steps:
      - checkout
      - run: git fetch --unshallow 2>/dev/null || true

  dependencies:
    machine:
      xcode:
        version: "8.3"
    steps:
      - restore_cache:
          key: dependency-cache
      - run: bin/bootstrap-if-needed
      - run: pod setup
      - save_cache:
          key: dependency-cache
          paths:
            - "Carthage"
            - "~/.cocoapods"

  test:
    machine:
      xcode:
        version: "8.3"
    steps:
      - run: bin/copy-secrets
      - run: bin/test
      - run: pod lib lint

workflows:
  version: 2
  test:
    jobs:
      - checkout
      - dependencies:
          requires:
            - checkout
      - test:
          requires:
            - dependencies
